### ISSUE TITLE
Copy writing Proposal

### ISSUE THREAD

**Issue by Gallantmayor** [jrawsthorne/review.app#1]
Hello, i just checked your lovely project and i discovered you have some sections missing out like FAQ, about us, contact us and privacy policy. If you dont mind i will like to write that for you.
My email: gallantmayor22@gmail.com

**Comment by jrawsthorne** [comment]
Hi, as the site isn't near production yet this isn't really needed but if I need help on it in the future I'll be sure to contact you. Thanks!
